name: polkawallet_plugin_chainx
description: The ChainX network flutter plugin for polkawallet app.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.0
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  json_annotation: ^3.0.1
  flutter_svg: ^0.19.3
  get_storage: ^1.2.1
  polkawallet_sdk: ^0.1.1
  #  polkawallet_sdk:
  #    path: ../sdk
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: 9ff8f1ebbaad3bbda904756f650414cf7cfe3163
#    path: ../ui

dev_dependencies:
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.1
  json_serializable: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/js_service_chainx/dist/main.js
    - assets/images/public/bg.png
    - assets/images/public/chainx.png
    - assets/images/public/chainx_gray.png
    - assets/images/public/staking.png
    - assets/images/public/staking_yellow.png
    - assets/images/public/governance.png
    - assets/images/public/governance_yellow.png
    - assets/images/public/nav_governance.svg
    - assets/images/public/nav_staking.svg
    - assets/images/staking/ok.png
    - assets/images/staking/error.png
    - assets/images/staking/reward.svg
    - assets/images/staking/slash.svg
    - assets/images/tokens/PCX.png
    - assets/images/public/polkassembly.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
